#!/bin/bash

FILE_TYPE=$1
FILE_NAME=$2
RES_FOLDER="$(dirname "$0")/.generate.res"

if [[ "$FILE_NAME" == ""  || "$FILE_TYPE" == "" ]]
then
    echo -e "$(tput setaf 1)ERROR:$(tput sgr0) wrong syntax. Use it like that:"
    echo -e "\t$(tput bold)generate$(tput sgr0) $(tput dim)<file type> <file name>$(tput sgr0)"
    exit 1
fi

case $FILE_TYPE in
    sh|script)
        touch $FILE_NAME
        chmod +x $FILE_NAME
        cat "$RES_FOLDER/script.template" > $FILE_NAME 
        echo -e "$(tput setaf 2)=== Script file $FILE_NAME was generated$(tput sgr0)"
        ;;
    *)
        echo -e "$(tput setaf 1)ERROR:$(tput sgr0) wrong file type! Available types:"
        echo -e "\t$(tput bold)sh, script$(tput sgr0) - creates script file template"
        exit 1
        ;;
esac

