#!/bin/bash

FILE_TYPE=$1
FILE_NAME=$2

if [[ "$FILE_NAME" == ""  || "$FILE_TYPE" == "" ]]
then
    echo -e "ERROR: wrong syntax. Use it like that:"
    echo -e "\tgenerate <file type> <file name>"
    exit 1
fi

case $FILE_TYPE in
    sh|script)
        echo -e "=== Generating script $FILE_NAME ==="
        touch $FILE_NAME
        chmod +x $FILE_NAME
        echo -e "#!/bin/bash\n" > $FILE_NAME
        echo -e "=== Script file $FILE_NAME was generated"
        ;;
    *)
        echo -e "ERROR: wrong file type! Available types:"
        echo -e "\tsh, script - creates script file template"
        exit 1
        ;;
esac

